checker/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', FilesListView.as_view(), name='files_list'),
    path('add_file/', AddFileView.as_view(), name='add_file'),
    path('detail_file/<int:pk>/', DetailFileView.as_view(), name='detail_file'),
    path('update_file/<int:pk>/', UpdateFileView.as_view(), name='update_file'),
    path('delete_file/<int:pk>/', DeleteFileView.as_view(), name='delete_file'),
]

cw_docker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('checker.urls')),
]

users/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('login', LoginUser.as_view(), name='login'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('logout/', logout_user, name='logout'),
]

checker/models.py
from django.conf import settings
from django.core.validators import FileExtensionValidator
from django.db import models


class FileStatus(models.TextChoices):
    NEW = 'new', 'Новый'
    UPDATED = 'updated', 'Обновленный'
    VERIFIED = 'verified', 'Подтвержденный'


class File(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Владелец')
    file = models.FileField(upload_to='files', validators=[FileExtensionValidator(['py'])], verbose_name='Файл')
    status = models.CharField(max_length=20, choices=FileStatus.choices, default=FileStatus.NEW, verbose_name='Статус')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Файл'
        verbose_name_plural = 'Файлы'
        ordering = ['status']

    def delete(self, *args, **kwargs):
        storage, path = self.file.storage, self.file.path
        super().delete(*args, **kwargs)
        storage.delete(path)


class Logs(models.Model):
    file = models.ForeignKey(File, on_delete=models.CASCADE, verbose_name='Файл')
    info = models.TextField(verbose_name='Информация')
    send_mail = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Лог'
        verbose_name_plural = 'Логи'
        ordering = ['created_at']

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from users.managers import UserManager


class UserRoles(models.TextChoices):
    ADMIN = 'admin', 'Администратор'
    USER = 'users', 'Пользователь'


class User(AbstractUser):
    email = models.EmailField(unique=True, verbose_name='Почта')
    role = models.CharField(max_length=20, choices=UserRoles.choices, default=UserRoles.USER, verbose_name='Роль')

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.email

checker/forms.py
from django import forms
from .models import File


class FileAddAndUpdateForm(forms.ModelForm):
    class Meta:
        model = File
        fields = ('file',)

users/forms.py
from django.contrib.auth.forms import UserCreationForm

from users.models import User


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'username', 'password1', 'password2',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})

checker/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from checker.forms import FileAddAndUpdateForm
from checker.models import File, Logs, FileStatus


class FilesListView(LoginRequiredMixin, ListView):
    login_url = 'login'
    template_name = 'checker/files_list.html'

    def get_queryset(self):
        return File.objects.filter(owner=self.request.user)


class AddFileView(LoginRequiredMixin, CreateView):
    login_url = 'login'
    form_class = FileAddAndUpdateForm
    template_name = 'checker/add_file.html'
    success_url = reverse_lazy('files_list')

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            file = form.save(commit=False)
            file.owner = self.request.user
            file.save()

        return redirect(self.success_url)


class DetailFileView(LoginRequiredMixin, DetailView):
    login_url = 'login'
    template_name = 'checker/detail_file.html'

    def get_object(self, *args, **kwargs):
        try:
            return Logs.objects.get(file_id=self.kwargs['pk'])
        except:
            return None


class UpdateFileView(LoginRequiredMixin, UpdateView):
    login_url = 'login'
    model = File
    form_class = FileAddAndUpdateForm
    template_name = 'checker/update_file.html'
    success_url = reverse_lazy('files_list')

    def post(self, request, *args, **kwargs):
        file = File.objects.get(id=self.kwargs['pk'])
        file.file.delete()
        super().post(request, *args, **kwargs)

        if self.form_valid:
            self.object.status = FileStatus.UPDATED
            self.object.save()

        return redirect(self.success_url)


class DeleteFileView(LoginRequiredMixin, DeleteView):
    login_url = 'login'
    model = File
    template_name = 'checker/delete_file.html'
    success_url = reverse_lazy('files_list')

users/views.py
from django.contrib.auth import logout
from django.contrib.auth.views import LoginView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView

from users.forms import CustomUserCreationForm


class RegisterUser(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'users/registration.html'
    success_url = reverse_lazy('login')


class LoginUser(LoginView):
    template_name = 'users/login.html'

    def get_success_url(self):
        return reverse_lazy('files_list')


def logout_user(request):
    logout(request)
    return redirect('login')

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} {% endblock %}</title>

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    {% block content %} {% endblock %}
</body>
</html>

templates/checker/add_file.html
{% extends 'base.html' %}

{% block content %}

    <div class="container h-100">
        <div class="col-lg-12 col-xl-11">
            <div class="card text-black">
                <div class="card-body p-md-5">
                    <div class="row justify-content-center">
                        <div class="col-md-10 col-lg-6">

                            <h1 class="text-center fw-bold mb-5 mx-1 mx-md-4 mt-4">Новый файл</h1>

                            <form action="" method="POST" enctype="multipart/form-data">
                                {% csrf_token %}

                                <div>
                                    <input class="form-control form-control-lg" type="file" name="file" required id="id_file">
                                </div>

                                <div class="d-flex justify-content-center align-items-center flex-column">
                                    <button class="btn btn-primary my-5" type="submit"> Добавить новый файл </button>
                                    <a class="btn btn-secondary" href="{% url 'files_list' %}">Назад</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

templates/checker/delete_file.html
{% extends 'base.html' %}

{% block content %}

    <div class="container h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-lg-12 col-xl-11">
                <div class="card text-black">
                    <div class="card-body p-md-5">
                        <div class="row justify-content-center">
                            <div class="col-md-10 col-lg-8">

                                <h1 class="text-center fw-bold mb-5 mx-1 mx-md-4 mt-4">Удалить файл</h1>
                                <h5 class="text-center mb-5 mx-1 mx-md-4 mt-4"> Вы действительно хотите удалить? {{ object.file }}?</h5>

                                <form class="form" action="" method="POST">
                                    {% csrf_token %}

                                    <div class="text-center mb-5 mx-1 mx-md-4 mt-4">
                                        <a class="btn btn-outline-dark" href="{% url 'files_list' %}">Назад</a>
                                        <button class="btn btn-primary">Удалить</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

templates/checker/detail_file.html
{% extends 'base.html' %}

{% block content %}

    <div class="container h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-lg-12 col-xl-11">
                <div class="card text-black">
                    <div class="card-body p-md-5">
                        <div class="row justify-content-center">
                            <div class="col-md-10 col-lg-12">

                                <h1 class="text-center fw-bold mb-5 mx-1 mx-md-4 mt-4">Логи</h1>

                                <hr>

                                {% if object %}
                                    <p class="text-center h3 fw-bold mb-5 mx-1 mx-md-4 mt-4">
                                        {{ object.file.file }}</p>
                                    <p class="text h4">Результат:</p>

                                    <br>
                                    <p class="text">{{ object.info}}</p>
                                    <br>

                                    {% if object.send_mail %}

                                        <div class="d-flex justify-content-center">
                                            <h3>Письмо отправлено на почту</h3>
                                        </div>

                                    {% else %}

                                        <div class="d-flex justify-content-center">
                                            <h3>Письмо не отправлено на почту</h3>
                                        </div>

                                    {% endif %}

                                {% else %}
                                    <div class="d-flex justify-content-center">
                                        <p class="text h3">Файл проверяется</p>
                                    </div>
                                {% endif %}

                                <hr>

                                <div class="text-center mt-5 mx-1 mx-md-4 mt-4">
                                    <a class="btn btn-outline-dark" href="{% url 'files_list' %}">Назад</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/checker/files_list.html
{% extends 'base.html' %}

{% block title %} Checker {% endblock %}

{% block content %}

    <header>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-primary">
            <div class="container-fluid justify-content-center">
                <ul class="navbar-nav">
                    <li class="nav-item ">
                        <a class="nav-link link-dark" href="{% url 'logout' %}">Выйти</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <main class="container">
        <div class="jumbotron">
            <div class="row justify-content-center align-items-center">
                <div class="col-15">
                    <div class="card">
                        <div class="card-header">
                            <h1>Список файлов</h1>
                        </div>

                        <div class="card-body">

                            <a class="btn btn-primary" href="{% url 'add_file' %}">Загрузить новый файл</a>

                            <table class="table">
                                <thead class="text-center">
                                    <tr>
                                        <td>Файл</td>
                                        <td>Статус</td>
                                        <td>Создан</td>
                                        <td>Обновлен</td>
                                    </tr>
                                </thead>

                                <tbody class="text-center">
                                    {% for item in object_list %}
                                        <tr>
                                            <td>
                                                <a class="nav-link" href="{% url 'detail_file' item.pk %}">
                                                    {{ item.file.name }}
                                                </a>
                                            </td>
                                            <td>{{ item.get_status_display }}</td>
                                            <td>{{ item.created_at }}</td>
                                            <td>{{ item.updated_at }}</td>

                                            <td>
                                                <a href="{% url 'update_file' item.id %}"
                                                   class="btn btn-primary">Обновить
                                                </a>

                                                <a href="{% url 'delete_file' item.id %}"
                                                   class="btn btn-secondary">Удалить
                                                </a>
                                            </td>

                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

{% endblock %}

templates/checker/update_file.html
{% extends 'base.html' %}

{% block content %}

    <div class="container h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-lg-12 col-xl-11">
                <div class="card text-black">
                    <div class="card-body p-md-5">
                        <div class="row justify-content-center">
                            <div class="col-md-10 col-lg-8">

                                <h1 class="text-center fw-bold mb-5 mx-1 mx-md-4 mt-4">Обновить файл</h1>
                                <h5 class="text-center mx-5 mx-md-4 mt-4">Текущий файл: {{ object.file }}</h5>

                                <form action="" method="POST" enctype="multipart/form-data">
                                    {% csrf_token %}

                                    <div>
                                        <input class="form-control form-control-lg mt-4" type="file" name="file" required id="id_file">
                                    </div>

                                    <div class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">
                                        <a class="btn btn-outline-dark" href="{% url 'files_list' %}">Назад</a>
                                        <button class="btn btn-primary">Обновить</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock%}

templates/users/login.html
{% extends 'base.html' %}

{% block title %} Авторизация {% endblock %}

{% block content %}

    <main class="form-signin text-center">
        <h1 class="h3 mb-3 fw-normal">Вход</h1>

        <form action="{% url 'login' %}" method="POST">
            {% csrf_token %}

            <div class="form-floating p-1">
                <input type="email" class="form-control" name="username" placeholder="Почта">
            </div>

            <div class="form-floating p-1">
                <input type="password" class="form-control" name="password" placeholder="Пароль">
            </div>

            <button class="btn btn-lg btn-primary button-access" type="submit">Войти</button>
            <a class="nav-link" href="{% url 'register' %}">Зарегистрироваться</a>
        </form>
    </main>

{% endblock %}

templates/users/registration.html
{% extends 'base.html' %}

{% block title %} Регистрация {% endblock %}

{% block content %}

    <main class="form-signin text-center">
        <h1 class="h3 mb-3 fw-normal">Регистрация</h1>

        <form action="{% url 'register' %}" method="POST">
            {% csrf_token %}

            <div class="form-floating p-2">
                <input type="email" class="form-control" name="email" placeholder="Почта">
            </div>

            <div class="form-floating p-2">
                <input type="text" class="form-control" name="username" placeholder="Логин">
            </div>

            <div class="form-floating p-2">
                <input type="password" class="form-control" name="password1" placeholder="Пароль">
            </div>

            <div class="form-floating p-2">
                <input type="password" class="form-control" name="password2" placeholder="Повторите пароль">
            </div>

            <button class="btn btn-lg btn-primary button-access" type="submit">Зарегистрироваться</button>
        </form>
    </main>

{% endblock %}